### ISSUE TITLE
Pass HDFS custom config parameters in charts

### ISSUE THREAD

**Issue by rporres** [apache-spark-on-k8s/kubernetes-HDFS#14]
Currently there's no way to pass custom config parameters to the hadoop docker images apart from what it's already there (e.g. `HDFS_CONF_dfs_datanode_data_dir`, `CLUSTER_NAME`)

In some setups it may be necessary to further config HDFS to make it work as expect. For example, in my case I've needed to tweak around `MULTIHOMED_NETWORK` parameters in order to restrict traffic to one of my interfaces (the servers I'm deploying in have two).

The simplest idea would be to add a `hadoop_env` map to the datanode and namenode charts and then range over it in the templates `containers.env` section but doing that we could overwrite some of the keys that are defined elsewhere (such as `HDFS_CONF_dfs_datanode_data_dir` that is controlled by `dataNodeHostPath`) so I'm unsure about the best approach for this.

I'm willing to send a patch that implement this feature provided we find a satisfying approach for it.

**Comment by kimoonkim** [comment]
Thanks @rporres for suggesting this. Yes, it is something we definitely want to do.

Regarding the potential config conflict with pre-defined keys like `HDFS_CONF_dfs_datanode_data_dir`, I think we could just determine reasonable precedence. Maybe the pre-defined keys should override user-supplied ones if they overlap, given that helm charts may fail to launch if some of the pre-defined keys are set incorrectly. To enforce this, we can simply set the pre-defined keys **after** the user-supplied ones are set. Please let me know what you think.

**Comment by rporres** [comment]
Hi @kimoonkim I'll take a look into your proposal to see if I can make it work. I will come back to you as soon as I've got something

**Comment by rporres** [comment]
Hi @kimoonkim Did you have a chance to take a look to the PR I sent a few days ago? Thx!

**Comment by kimoonkim** [comment]
Ah, I somehow missed the PR. Thanks for letting me know. I'll take a look shortly.
