### ISSUE TITLE
remove hdfs-resolv-conf?

### ISSUE THREAD

**Issue by jpiper** [apache-spark-on-k8s/kubernetes-HDFS#19]
with the addition of `ClusterFirstWithHostNet` in #16 is the `hdfs-resolv-conf` still needed?

**Comment by kimoonkim** [comment]
Thanks for opening the issue.

You're right. I believe we don't need hdfs-resolv-conf any more. I was hoping to get to that soon :-)

If you happen to have a PR, we'll be glad to take a look!

**Comment by jpiper** [comment]
Sure thing, PR opened (minus some git issues I was having)
