### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by kimoonkim** [apache-spark-on-k8s/kubernetes-HDFS#25]
There is no automated CI for HDFS-on-K8s. Let's add one.

**Comment by kimoonkim** [comment]
We learned travis CI now supports minikube. ([blog](https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube)) This could be useful for our CI as contributors can easily run integration tests using a minikube.

**Comment by kimoonkim** [comment]
I played with travis + minkube. And success! The following is from inside a travis build ([link](https://travis-ci.org/kimoonkim/kubernetes-HDFS/builds/359574323)].

```
$ kubectl cluster-info
Kubernetes master is running at https://10.20.0.7:8443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The command "kubectl cluster-info" exited with 0.
0.40s$ kubectl run travis-example --image=redis
deployment "travis-example" created
The command "kubectl run travis-example --image=redis" exited with 0.
0.32s$ kubectl get deployment
NAME             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
travis-example   1         1         1            0           0s
The command "kubectl get deployment" exited with 0.
Done. Your build exited with 0.
```

CC @cvpatel @foxish @erikerlandson

**Comment by foxish** [comment]
That is awesome. Thanks for testing that. We should probably use that
moving forward for all single node testing. cc/ @dimberman

**Comment by kimoonkim** [comment]
Yes, airflow and other k8s projects can benefit from this.

@foxish I want to hook up travis in this repo `apache-spark-on-k8s/kubernetes-HDFS`. Currently I only see the `spark` repo under https://travis-ci.org/apache-spark-on-k8s/. Maybe you can enable travis in the settings page of the `kubernetes-HDFS` repo?

FYI, my fork settings/installations page, https://github.com/kimoonkim/kubernetes-HDFS/settings/installations, has the following:

```
Installed GitHub Apps
GitHub Apps augment and extend your workflows on GitHub with commercial, open source, and homegrown tools.

Services
Services are pre-built integrations that perform certain actions when events occur on GitHub.

Travis CI
```

Or, if I can be made admin of this repo, I can do it myself.

**Comment by foxish** [comment]
Made you an org owner.

**Comment by kimoonkim** [comment]
Thanks. I see the settings button now.

**Comment by kimoonkim** [comment]
Seems to work. #34 triggered a build.
