### ISSUE TITLE
java.net.NoRouteToHostException when trying to access HDFS from another pod

### ISSUE THREAD

**Issue by sumansomasundar** [apache-spark-on-k8s/kubernetes-HDFS#26]
I have setup a 2 node kubernetes cluster (1 master and 1 slave). I have namenode and datanode pods running on the slave node. I can access HDFS from both these pods. However when I try to access HDFS from a different pod (for example, hadoop pod) I get the following error:

```
$ kubectl exec -it hadoop bash
root@hadoop:/# hadoop fs  \
>     -fs hdfs://hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local  \
>     -ls /                     
ls: No Route to Host from  hadoop/10.244.1.171 to hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local:8020 failed on socket timeout exception: java.net.NoRouteToHostException: No route to host; For more details see:  http://wiki.apache.org/hadoop/NoRouteToHost
root@hadoop:/# 
```

**Comment by kimoonkim** [comment]
Hi @sumansomasundar. Thanks for trying out kube-hdfs.

I have not seen the particular error myself before. But I wonder if it's an issue with the kube-dns issue. Can you try the steps in https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#running-commands-in-a-pod, and then https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#does-the-service-work-by-dns? In my busybox pod, I can get the following:

```
$ kubectl exec -it busybox /bin/bash

 # nslookup hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local
Address 1: 192.168.6.157 hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local
```

And in the same busybox pod, `wget` will give me 404 error as opposed to the routing error, which means it was able to connect to the namenode:

```
# wget -qO- hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local:8020
wget: server returned error: HTTP/1.1 404 Not Found
```

**Comment by sumansomasundar** [comment]
@kimoonkim Thanks for the reply. 
It looks like the kube-dns is working fine. I get the following from my busybox:
```
kubectl run -i --tty busybox --image=busybox --generator="run-pod/v1"
If you don't see a command prompt, try pressing enter.
/ # 
/ # nslookup hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local
Address 1: 10.196.10.67 hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local
/ # wget -qO- hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local:8020
wget: can't connect to remote host (10.196.10.67): No route to host
```

However from the namenode pod, I get the following:
```
kubectl exec -it hdfs-namenode-0 bash
root@bus00epb:/# curl hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local:8020 
It looks like you are making an HTTP request to a Hadoop IPC port. This is not the correct port for the web interface on this daemon.
```

**Comment by kimoonkim** [comment]
I agree `kube-dns` seems to work. But `wget` output is concerning. I believe "No route to host" is the same error that you saw from the `hadoop fs` command.

I think your kubernetes setup somehow lack the pod to cluster-node route capability. The namenode daemon is attached to the physical IP address of cluster node (I believe `10.196.10.67` is one associated with a cluster node) The datanode daemons are also attached to physical IPs. So they can communicate with each other. But regular pods like busybox and your hadoop pod get unique virtual IP addresses. These pod IP addresses `should` be able to talk to physical IP daemons. Kubernetes supports this. But somehow it seems broken in your setup.

In my busybox, I can even issue `ping` or `traceroute` command to the namenode IP address. Can you also try them using your IP `10.196.10.67` please?
```
$ kubectl exec -it busybox /bin/sh
/ # nslookup hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local
Address 1: 192.168.6.157 hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local
/ # ping 192.168.6.157
PING 192.168.6.157 (192.168.6.157): 56 data bytes
64 bytes from 192.168.6.157: seq=0 ttl=63 time=0.537 ms
64 bytes from 192.168.6.157: seq=1 ttl=63 time=0.553 ms
^C
--- 192.168.6.157 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.537/0.545/0.553 ms
/ # traceroute 192.168.6.157
traceroute to 192.168.6.157 (192.168.6.157), 30 hops max, 46 byte packets
 1  ip-10-40-0-0.ec2.internal (10.40.0.0)  0.004 ms  0.002 ms  0.002 ms
 2  hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local (192.168.6.157)  0.408 ms  0.487 ms  0.358 ms
```

**Comment by sumansomasundar** [comment]
@kimoonkim It was a firewall issue. I added couple of rules for iptables in the cluster nodes and it worked.

Thanks for the help.

**Comment by kimoonkim** [comment]
Ah, that makes sense. Good to know firewalls can be a factor.
