### ISSUE TITLE
Unable to use with Kubernetes 1.14

### ISSUE THREAD

**Issue by falken** [apache-spark-on-k8s/kubernetes-HDFS#70]
When we attempt to deploy the chart on top of 1.14.1 we get the following error:

Error: validation failed: error validating "": error validating data: ValidationError(StatefulSet.spec): unknown field "terminationGracePeriodSeconds" in io.k8s.api.apps.v1beta1.StatefulSetSpec

We tracked this down to the Zookeeper chart. If we update the requirements.yaml to use 1.3.1 of the Zookeeper chart instead of 1.0.0 we no longer get the issue.

**Comment by kimoonkim** [comment]
Closing the issue. Thanks for finding out and fixing it.
